BEGIN; 

DROP TABLE IF EXISTS "user",
"category",
"tracking",
"role",
"article",
"order",
"picture",
"article_has_order",
"article_has_category";

-- -----------------------------------------------------
-- Table "answer"
-- -----------------------------------------------------
CREATE TABLE "category" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL UNIQUE,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


-- -----------------------------------------------------
-- Table "quiz"
-- -----------------------------------------------------
CREATE TABLE "role" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL UNIQUE,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "quiz_has_tag"
-- -----------------------------------------------------
CREATE TABLE "picture" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "url" text NOT NULL UNIQUE,
  "description" text NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


-- -----------------------------------------------------
-- Table "level"
-- -----------------------------------------------------
CREATE TABLE "user" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "firstname" text NOT NULL,
  "lastname" text NOT NULL,
  "email" text NOT NULL UNIQUE,
  "password" text NOT NULL,
  "role_id" integer NOT NULL REFERENCES "role"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


-- -----------------------------------------------------
-- Table "question"
-- -----------------------------------------------------
CREATE TABLE "article" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "description" text NOT NULL,
  "price" numeric NOT NULL,
  "available" boolean NOT NULL,
  "picture_id" integer NOT NULL REFERENCES "picture"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);

-- -----------------------------------------------------
-- Table "tag"
-- -----------------------------------------------------
CREATE TABLE "order" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_summary" text NOT NULL,
  "date" date NOT NULL,
  "price" numeric NOT NULL,
  "user_id" integer NOT NULL REFERENCES "user"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


-- -----------------------------------------------------
-- Table "app_user"
-- -----------------------------------------------------
CREATE TABLE "tracking" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "growth" text NOT NULL,
  "status" text NOT NULL,
  "plant_place" text NOT NULL,
  "picture_id" integer NOT NULL REFERENCES "picture"("id"),
  "order_id" integer NOT NULL REFERENCES "order"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz
);


CREATE TABLE "article_has_category" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "category_id" integer NOT NULL REFERENCES "category"("id"),
  "article_id" integer NOT NULL REFERENCES "article"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  UNIQUE ("article_id", "category_id")
);

CREATE TABLE "article_has_order" (
  "id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "quantity" numeric NOT NULL,
  "article_id" integer NOT NULL REFERENCES "article"("id"),
  "order_id" integer NOT NULL REFERENCES "order"("id"),
  "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamptz,
  UNIQUE ("article_id", "order_id")
);

COMMIT;